name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: unbuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multi-line script
        run: |
          node -v
          npm -v
           
